import type { Metadata } from "next";
import "./globals.css";
import ReduxProvider from "./_providers/redux-provider/redux-provider";
import { cn } from "@/lib/utils";
import Header from "@/components/globals/header";
import QueryProvider from "./_providers/query-provider/query-provider";
import { inter } from "./font";
import { Toaster } from "react-hot-toast";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <ReduxProvider>
        <QueryProvider>
          <body className={cn(inter.className, "flex flex-col min-h-screen min-w-screen custom-scroller")}>
            <Header />

              <main className="flex h-full min-h-[calc(100vh-71px)] w-full flex-grow flex-col items-center justify-start">

              <div className="flex w-full flex-grow flex-col items-center justify-start p-[11px_11px_40px] sm:py-8 max-w-7xl lg:max-w-8xl sm:px-10">

                {children}

              </div>

              <Toaster />
              
            </main>
          </body>
        </QueryProvider>
      </ReduxProvider>
    </html>
  );
}
